### PR TITLE
Correcting implementation of soundex algorithm

### PR DESCRIPTION
**Pull request by grossadamm**
There were a number of issues with the original implementation:
- i instead of l on a replace
- infinite loops
- incorrect results

As I started attempting to fix it, it became far easier to just re-implement the algorithm from the ground-up. I also added a number of test cases.

### CODE REVIEW

**Comment by grossadamm** [comment]
Anything needed for a merge?

**Comment by mindaslab** [comment]
@grossadamm Checking what changes you have made. Please wait..... Any way thanks for contributing.

**Comment by grossadamm** [comment]
@mindaslab I believe I had problems with the name "Kaylee". Any word with an L in it would have been incorrect I believe. Also, a number of the examples given on https://en.wikipedia.org/wiki/Soundex were failing. I don't recall the exact ones. 

Thank you for merging though!

**Comment by mindaslab** [comment]
@grossadamm  Okay, any way thanks a lot, the gems are available in http://rubygems.org

**Pull request merged**
